export const CAR_MODELS = [
    { name: "Alto", seats: "5", price: "₹1,000", image: "/images/cars/alto-k10.jpg" },
    { name: "Alto New", seats: "5", price: "₹1,200", image: "/images/cars/alto-k10.jpg" },
    { name: "Alto K10", seats: "5", price: "₹1,500", image: "/images/cars/alto-k10.jpg" },
    { name: "Celerio", seats: "5", price: "₹1,600", image: "/images/cars/celerio.jpg" },
    { name: "Celerio Red", seats: "5", price: "₹1,700", image: "/images/cars/celerio-red.jpg" },
    { name: "Swift LXI", seats: "5", price: "₹1,700", image: "/images/cars/maruti-swift-lxi.jpg" },
    { name: "Swift New", seats: "5", price: "₹2,000", image: "/images/cars/maruti-swift-new.webp" },
    { name: "Dzire LXI", seats: "5", price: "₹1,800", image: "/images/cars/dzire-lxi.jpg" },
    { name: "Dzire VXI", seats: "5", price: "₹2,000", image: "/images/cars/dzire-vxi.JPG" },
    { name: "Dzire Top", seats: "5", price: "₹2,200", image: "/images/cars/dzire-top.JPG" },
    { name: "Baleno", seats: "5", price: "₹2,000", image: "/images/cars/maruti-baleno.png" },
    { name: "Baleno Top", seats: "5", price: "₹2,200", image: "/images/cars/maruti-baleno.png" },
    { name: "Honda Amaze", seats: "5", price: "₹2,100", image: "/images/cars/honda-amaze.jpg" },
    { name: "Tata Tigor", seats: "5", price: "₹2,100", image: "/images/cars/tata-tigor.jpg" },
    { name: "Hyundai Exter", seats: "5", price: "₹2,500", image: "/images/cars/hyundai-exter.jpg" },
    { name: "i20 Sunroof", seats: "5", price: "₹2,500", image: "/images/cars/i20-sunroof.jpg" },
    { name: "Nexon Sunroof", seats: "5", price: "₹2,700", image: "/images/cars/nexon-sunroof.jpg" },
    { name: "Brezza Top", seats: "5", price: "₹2,600", image: "/images/cars/brezza-top.jpg" },
    { name: "Brezza Sunroof", seats: "5", price: "₹3,000", image: "/images/cars/brezza-sunroof.jpg" },
    { name: "Venue", seats: "5", price: "₹2,700", image: "/images/cars/venue.jpg" },
    { name: "Ertiga", seats: "7", price: "₹2,700", image: "/images/cars/ertiga.jpg" },
    { name: "Ertiga Top", seats: "7", price: "₹2,800", image: "/images/cars/ertiga-top.jpg" },
    { name: "XL6", seats: "6", price: "₹2,600", image: "/images/cars/xl6.jpg" },
    { name: "Scorpio S11 Black", seats: "7", price: "₹5,000", image: "/images/cars/mahindra-scorpio.png" },
    { name: "Thar 4x4", seats: "4", price: "₹5,000", image: "/images/cars/thar-4x4.jpg" },
    { name: "Roxx", seats: "5", price: "₹8,000", image: "/images/cars/mahindra-thar-roxx.jpg" },
];
